# --- Qatten specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
#epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "qplex_curiosity_vdn_learner_cds"
double_q: True
mixer: "dmaq_qatten"
mixing_embed_dim: 32
hypernet_embed: 64
adv_hypernet_layers: 1
adv_hypernet_embed: 64

num_kernel: 4
is_minus_one: True
is_adv_attention: True
is_stop_gradient: True

n_head: 4 # attention head number
attend_reg_coef: 0.001 # attention regulation coefficient  # For MMM2 and 3s5z_vs_3s6z, it is 0.001
state_bias: True # the constant value cs in the paper
mask_dead: False
weighted_head: False # weighted head Q-values, for MMM2 and 3s5z_vs_3s6z, it is True
nonlinear: False # non-linearity, for MMM2, it is True

num_circle: 1

# --- Agent parameters for cds ---
agent: "rnn_sd" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: False # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation
mac: "basic_mac_cds" # Basic controller (cds)
#----------------------------------

# --- hyper parameters for cds ---
beta1: 2.
beta2: 1.
beta: .07
anneal: False
anneal_rate: 3.
# --------------------------------

burn_in_period: 100

name: "qplex_qatten_sc2"
