# From https://github.com/wjh720/QPLEX/
# --- Qatten specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000
batch_size: 32

lr: 0.0005

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "dmaq_qatten_learner"
double_q: True
mixer: "dmaq"
mixing_embed_dim: 32
hypernet_embed: 64
#adv_hypernet_layers: 3
adv_hypernet_layers: 2
adv_hypernet_embed: 64

#num_kernel: 10
num_kernel: 4
is_minus_one: True
weighted_head: True
is_adv_attention: True
is_stop_gradient: True

use_rnn: True
obs_agent_id: True
obs_individual_obs: False

# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True
evaluation_epsilon: 0.0

name: "qplexH4"